//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Devices::AllJoyn;
using namespace Windows::Foundation;
using namespace org::allseen::LSF::ControllerService::LampGroup;

void LampGroupSignals::Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId)
{
    m_busObject = busObject;
    m_sessionId = sessionId;

    auto interfaceDefinition = alljoyn_busattachment_getinterface(alljoyn_busobject_getbusattachment(busObject), "org.allseen.LSF.ControllerService.LampGroup");
    alljoyn_interfacedescription_getmember(interfaceDefinition, "LampGroupsNameChanged", &m_memberLampGroupsNameChanged);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "LampGroupsCreated", &m_memberLampGroupsCreated);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "LampGroupsUpdated", &m_memberLampGroupsUpdated);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "LampGroupsDeleted", &m_memberLampGroupsDeleted);
}

void LampGroupSignals::LampGroupsNameChanged(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberLampGroupsIDs)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberLampGroupsIDs);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberLampGroupsNameChanged,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void LampGroupSignals::CallLampGroupsNameChangedReceived(_In_ LampGroupSignals^ sender, _In_ LampGroupLampGroupsNameChangedReceivedEventArgs^ args)
{
    LampGroupsNameChangedReceived(sender, args);
}

void LampGroupSignals::LampGroupsCreated(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberLampGroupsIDs)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberLampGroupsIDs);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberLampGroupsCreated,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void LampGroupSignals::CallLampGroupsCreatedReceived(_In_ LampGroupSignals^ sender, _In_ LampGroupLampGroupsCreatedReceivedEventArgs^ args)
{
    LampGroupsCreatedReceived(sender, args);
}

void LampGroupSignals::LampGroupsUpdated(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberLampGroupsIDs)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberLampGroupsIDs);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberLampGroupsUpdated,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void LampGroupSignals::CallLampGroupsUpdatedReceived(_In_ LampGroupSignals^ sender, _In_ LampGroupLampGroupsUpdatedReceivedEventArgs^ args)
{
    LampGroupsUpdatedReceived(sender, args);
}

void LampGroupSignals::LampGroupsDeleted(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberLampGroupsIDs)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberLampGroupsIDs);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberLampGroupsDeleted,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void LampGroupSignals::CallLampGroupsDeletedReceived(_In_ LampGroupSignals^ sender, _In_ LampGroupLampGroupsDeletedReceivedEventArgs^ args)
{
    LampGroupsDeletedReceived(sender, args);
}

