//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace LSF { namespace ControllerService {

ref class ControllerServiceLegacySignals;

public interface class IControllerServiceLegacySignals
{
    event Windows::Foundation::TypedEventHandler<ControllerServiceLegacySignals^, ControllerServiceControllerServiceLightingResetReceivedEventArgs^>^ ControllerServiceLightingResetReceived;
};

public ref class ControllerServiceLegacySignals sealed : [Windows::Foundation::Metadata::Default] IControllerServiceLegacySignals
{
public:
    // Calling this method will send the ControllerServiceLightingReset signal to every member of the session.
    void ControllerServiceLightingReset();

    // This event fires whenever the ControllerServiceLightingReset signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<ControllerServiceLegacySignals^, ControllerServiceControllerServiceLightingResetReceivedEventArgs^>^ ControllerServiceLightingResetReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<ControllerServiceLegacySignals^, ControllerServiceControllerServiceLightingResetReceivedEventArgs^>^ handler) 
        { 
            return _ControllerServiceLightingResetReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<ControllerServiceLegacySignals^>(sender), safe_cast<ControllerServiceControllerServiceLightingResetReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _ControllerServiceLightingResetReceived -= token; 
        } 
    internal: 
        void raise(ControllerServiceLegacySignals^ sender, ControllerServiceControllerServiceLightingResetReceivedEventArgs^ args) 
        { 
            _ControllerServiceLightingResetReceived(sender, args);
        } 
    }

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallControllerServiceLightingResetReceived(_In_ ControllerServiceLegacySignals^ sender, _In_ ControllerServiceControllerServiceLightingResetReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _ControllerServiceLightingResetReceived;

    alljoyn_interfacedescription_member m_memberControllerServiceLightingReset;
};

} } } } 