//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Devices::AllJoyn;
using namespace Windows::Foundation;
using namespace org::allseen::LSF::ControllerService::Preset;

void PresetSignals::Initialize(_In_ org::allseen::LSF::ISignalEmitter^ emitter)
{
    m_emitter = emitter;
    alljoyn_busattachment nativeBusAttachment = AllJoynHelpers::GetInternalBusAttachment(m_emitter->BusObject->BusAttachment);
    auto interfaceDefinition = alljoyn_busattachment_getinterface(nativeBusAttachment, "org.allseen.LSF.ControllerService.Preset");
    alljoyn_interfacedescription_getmember(interfaceDefinition, "DefaultLampStateChanged", &m_memberDefaultLampStateChanged);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "PresetsNameChanged", &m_memberPresetsNameChanged);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "PresetsCreated", &m_memberPresetsCreated);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "PresetsUpdated", &m_memberPresetsUpdated);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "PresetsDeleted", &m_memberPresetsDeleted);
}

void PresetSignals::DefaultLampStateChanged()
{
    if (nullptr == AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject))
    {
        return;
    }

    size_t argCount = 0;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    
    alljoyn_busobject_signal(
        AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject), 
        NULL,  // Generated code only supports broadcast signals.
        m_emitter->Session->Id,
        m_memberDefaultLampStateChanged,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void PresetSignals::CallDefaultLampStateChangedReceived(_In_ PresetSignals^ sender, _In_ PresetDefaultLampStateChangedReceivedEventArgs^ args)
{
    DefaultLampStateChangedReceived(sender, args);
}

void PresetSignals::PresetsNameChanged(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberPresetIDs)
{
    if (nullptr == AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject))
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberPresetIDs);
    
    alljoyn_busobject_signal(
        AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject), 
        NULL,  // Generated code only supports broadcast signals.
        m_emitter->Session->Id,
        m_memberPresetsNameChanged,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void PresetSignals::CallPresetsNameChangedReceived(_In_ PresetSignals^ sender, _In_ PresetPresetsNameChangedReceivedEventArgs^ args)
{
    PresetsNameChangedReceived(sender, args);
}

void PresetSignals::PresetsCreated(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberPresetsIDs)
{
    if (nullptr == AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject))
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberPresetsIDs);
    
    alljoyn_busobject_signal(
        AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject), 
        NULL,  // Generated code only supports broadcast signals.
        m_emitter->Session->Id,
        m_memberPresetsCreated,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void PresetSignals::CallPresetsCreatedReceived(_In_ PresetSignals^ sender, _In_ PresetPresetsCreatedReceivedEventArgs^ args)
{
    PresetsCreatedReceived(sender, args);
}

void PresetSignals::PresetsUpdated(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberPresetsIDs)
{
    if (nullptr == AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject))
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberPresetsIDs);
    
    alljoyn_busobject_signal(
        AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject), 
        NULL,  // Generated code only supports broadcast signals.
        m_emitter->Session->Id,
        m_memberPresetsUpdated,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void PresetSignals::CallPresetsUpdatedReceived(_In_ PresetSignals^ sender, _In_ PresetPresetsUpdatedReceivedEventArgs^ args)
{
    PresetsUpdatedReceived(sender, args);
}

void PresetSignals::PresetsDeleted(_In_ Windows::Foundation::Collections::IVectorView<Platform::String^>^ interfaceMemberPresetsIDs)
{
    if (nullptr == AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject))
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "as", interfaceMemberPresetsIDs);
    
    alljoyn_busobject_signal(
        AllJoynHelpers::GetInternalBusObject(m_emitter->BusObject), 
        NULL,  // Generated code only supports broadcast signals.
        m_emitter->Session->Id,
        m_memberPresetsDeleted,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void PresetSignals::CallPresetsDeletedReceived(_In_ PresetSignals^ sender, _In_ PresetPresetsDeletedReceivedEventArgs^ args)
{
    PresetsDeletedReceived(sender, args);
}

